
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v2.0.0.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace TypeType.Tui
{
    using System;
    using Terminal.Gui;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Drawing;


    public partial class GameView : Toplevel
    {
        private Terminal.Gui.TextView textView;

        private Terminal.Gui.StatusBar statusBar;

        private Terminal.Gui.Shortcut f1EditMe;

        private void InitializeComponent()
        {
            this.statusBar = new Terminal.Gui.StatusBar();
            this.textView = new Terminal.Gui.TextView();
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Visible = true;
            this.Arrangement = (Terminal.Gui.ViewArrangement.Movable | Terminal.Gui.ViewArrangement.Overlapped);
            this.Modal = false;
            this.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Title = "Menu";
            this.textView.Width = 62;
            this.textView.Height = 17;
            this.textView.X = Pos.Center();
            this.textView.Y = Pos.Center();
            this.textView.Visible = true;
            this.textView.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.textView.AllowsTab = true;
            this.textView.AllowsReturn = true;
            this.textView.WordWrap = true;
            this.textView.Data = "textView";
            this.textView.Text = "Golf is so popular simply because it is the best game in the world at which to be" +
                " bad.";
            this.textView.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.textView);
            this.statusBar.Width = Dim.Fill(0);
            this.statusBar.Height = Dim.Auto();
            this.statusBar.X = 0;
            this.statusBar.Y = Pos.AnchorEnd(0);
            this.statusBar.Visible = true;
            this.statusBar.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.statusBar.Data = "statusBar";
            this.statusBar.Text = "";
            this.statusBar.TextAlignment = Terminal.Gui.Alignment.Start;
            this.f1EditMe = new Terminal.Gui.Shortcut(((Terminal.Gui.KeyCode)(1114223u)), "F1 - Edit Me", null);
            this.statusBar.Add(this.f1EditMe);
            this.Add(this.statusBar);
        }
    }
}
