
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v2.0.0.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace TypeType.Tui
{
    using CommunityToolkit.Mvvm.Messaging;
    using Terminal.Gui;
    using TypeType.Tui.ViewModels;

    public partial class GameView
    {

        public GameView(GameViewModel viewModel)
        {
            // WeakReferenceMessenger.Default.Register(this);
            Title = "Game View";
            ViewModel = viewModel;
            InitializeComponent();

            textView.ReadOnly = true;
            textView.KeyDown += (_, k) =>
            {
                ViewModel.LastKeyPressed = k;
            };
            this.Loaded += (_, _) =>
            {
                ViewModel.LoadCommand.Execute(null);
            };

        }

        public GameViewModel ViewModel { get; set; }

        // public void Receive(Message)
    }


}
